global using Amazon.Extensions.NETCore.Setup;
global using Amazon.S3;
global using Amazon.S3.Model;
global using _dotnetaws;
global using Microsoft.Extensions.Options;
global using DotNetEnv;
global using System.Net;
global using Microsoft.AspNetCore.Mvc;
global using Scalar.AspNetCore;
